server:
  port: 9000
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://euk1:8082/eureka,http://euk1:8083/eureka
management:
  endpoints:
    web:
      exposure:
        include: beans,conditions,env,info,threaddump,httptrace,hystrix.stream

#ribbon 默认使用RoundRobinRule轮询算法来负载均衡，可以通过以下配置修改
#负载均衡算法都需要实现IRule 接口
user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true