server:
  port: 8083
eureka:
  instance:
    hostname: euk3
    virtual-host-name: euk
  client:
    service-url:
      defaultZone: http://euk1:8081/eureka,http://euk1:8082/eureka

spring:
  application:
    name: euk
