spring:
  application:
    name: zuul-server
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://euk1:8082/eureka,http://euk1:8083/eureka
zuul:
  prefix: /api/v1/
#  strip-prefix: true